### ISSUE TITLE
dependency on smartmontools pulls unneeded packages on virtual servers

### ISSUE THREAD

**Issue by hbos** [ossobv/gocollect#2]
`Depends: libc6 (>= 2.2.5), dmidecode, iproute | iproute2, kmod | module-init-tools, lshw, openssh-client, smartmontools`

Dependency on smartmontools pulls unneeded packages on virtual servers.

Possible solution would be creating an additional (meta)package for hardware servers.

**Comment by wdoekes** [comment]
Closed when fixing #1.
